name: Build VCamera APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Debug APK
        run: |
          gradle clean assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: VCamera-debug
          path: app/build/outputs/apk/debug/app-debug.apk
